In [1]:
import numpy as np

In [2]:
arr=np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
# random distribution
a=np.random.randn(10)

In [7]:
b=np.random.randn(10)

In [8]:
a

array([ 1.3624377 ,  1.71692397,  1.39314861,  0.95681176, -0.83098698,
        0.12342669, -0.6134256 ,  0.00532232,  0.51808052, -0.54440784])

In [9]:
b

array([ 1.92790844,  0.0803067 , -1.69034077, -0.65949947, -0.86912953,
       -0.58847929, -1.17734913, -1.21711509,  0.16068945, -0.04291582])

In [10]:
np.add(a,b)

array([ 3.29034614,  1.79723067, -0.29719216,  0.29731229, -1.70011651,
       -0.4650526 , -1.79077473, -1.21179277,  0.67876997, -0.58732366])

In [11]:
np.maximum(a,b)

array([ 1.92790844,  1.71692397,  1.39314861,  0.95681176, -0.83098698,
        0.12342669, -0.6134256 ,  0.00532232,  0.51808052, -0.04291582])

In [12]:
np.minimum(a,b)

array([ 1.3624377 ,  0.0803067 , -1.69034077, -0.65949947, -0.86912953,
       -0.58847929, -1.17734913, -1.21711509,  0.16068945, -0.54440784])

In [13]:
np.sum(a.b)

AttributeError: 'numpy.ndarray' object has no attribute 'b'

In [14]:
np.sum(a,b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [15]:
np.maximum(a,b,axis=0)

TypeError: 'axis' is an invalid keyword to ufunc 'maximum'

In [16]:
np.maximum(a,b,0)

TypeError: return arrays must be of ArrayType

In [17]:
a.max(axis=0)

1.71692397160702

In [18]:
arr2d=np.array([[1,2,3],[4,5,6]])

In [19]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr2d.max(axis=0)

array([4, 5, 6])

In [21]:
arr2d.max(axis=1)

array([3, 6])

In [22]:
arr2d.max(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2