In [1]:
import numpy as np

In [2]:
arr=np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarr',arr)

In [5]:
arr

array([0, 1, 2, 3, 4])

In [6]:
np.load('myarr.npy')

array([0, 1, 2, 3, 4])

In [7]:
arr1=np.load('myarr,npy')

IOError: [Errno 2] No such file or directory: 'myarr,npy'

In [8]:
arr1=np.load('myarr.npy')

In [9]:
arr2=arr

In [10]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [11]:
archieve_arr=np.load('ziparray.npz')

In [12]:
archieve_arr

In [13]:
archieve_arr['x']

array([0, 1, 2, 3, 4])

In [14]:
archieve_arr['y']

array([0, 1, 2, 3, 4])

In [15]:
a3=np.array([[1,2,3],[4,5,6]])

In [16]:
np.savetxt('mytxtarr.txt',a3,delimiter=',')

In [17]:
a4=np.loadtxt('mytxtarr.txt',delimiter='|')

ValueError: invalid literal for float(): 1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00

In [18]:
a4=np.loadtxt('mytxtarr.txt',delimiter=',')

In [19]:
a4

array([[1., 2., 3.],
       [4., 5., 6.]])