In [1]:
import numpy as np

In [2]:
5/2

2

In [3]:
from __future__ import division

In [4]:
5/2

2.5

In [6]:
arr=np.array([1,2,3],[4,5,6])

TypeError: data type not understood

In [7]:
arr1=np.array([1,2,3],[4,5,6])

TypeError: data type not understood

In [8]:
arr=np.array([[1,2,3],[4,5,6]])

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [13]:
arr** 3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [14]:
arr*3

array([[ 3,  6,  9],
       [12, 15, 18]])