Indexing one-D array

In [1]:
import numpy as np

In [2]:
arr1D=np.arange(0,11)

In [3]:
arr1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr1D[8]

8

In [5]:
arr1D[1:5]

array([1, 2, 3, 4])

Slicing, it changes the oringinal array, In order to avoid changes in original array use arr.copy()

In [6]:
slice_arr=arr[0:5]

NameError: name 'arr' is not defined

In [7]:
slice_arr=arr(0:5)

SyntaxError: invalid syntax (<ipython-input-7-b4ad692b6c19>, line 1)

In [8]:
slice_arr=arr1D[0:6]

In [9]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_arr[:]=99

In [11]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
arr1D

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
slice2=arr.copy()

NameError: name 'arr' is not defined

In [14]:
slice2=arr1d.copy()

NameError: name 'arr1d' is not defined

In [15]:
slice2=arr1D.copy()

In [16]:
slice2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
slice2[3:7]=77

In [18]:
slice2

array([99, 99, 99, 77, 77, 77, 77,  7,  8,  9, 10])

In [19]:
slice3=slice2[8:9]

In [20]:
slice3[:]=33

In [21]:
slice3

array([33])

In [22]:
slice2

array([99, 99, 99, 77, 77, 77, 77,  7, 33,  9, 10])

In [23]:
arr1D

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing on 2D array

In [24]:
arr2D=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [25]:
arr2D


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr2D[2]

array([7, 8, 9])

In [27]:
arr2D[2:1]

array([], shape=(0L, 3L), dtype=int32)

In [28]:
arr2D[1][2]

6

In [29]:
slice2d=arr2D[:2,1:]

In [31]:
slice2d

array([[2, 3],
       [5, 6]])

In [32]:
slice2d_2=arr2D[1:3,1:]

In [33]:
slice2d_2

array([[5, 6],
       [8, 9]])

In [34]:
arrzero=np.zeros((10,10))

In [35]:
arrzero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
arr_len=arrzero.shape(1)

TypeError: 'tuple' object is not callable

In [37]:
arr_len=arrzero.shape[3]

IndexError: tuple index out of range

In [38]:
arr_len=arrzero.shape[2]

IndexError: tuple index out of range

In [39]:
arr_len=arrzero.shape[0]

In [40]:
arr_len

10L

In [43]:
for i in range(arr_len):
    
    arrzero[i]=1

In [44]:
arrzero

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
for i in range(arr_len):
    arrzero[i]=i

In [47]:
arrzero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])